USE eutopia_db;

INSERT INTO Users (userID, firstName, lastName, email, countryOrigin, createdBy, updatedBy) 
VALUES
  (1, 'Abramo', 'Giacomo', 'agiacomo0@naver.com', 'Belgium', 1, 1),
  (2, 'Dev', 'Andreacci', 'dandreacci1@rambler.ru', 'Czech Republic', 2, 2),
  (3, 'Aloysia', 'Hellmore', 'ahellmore2@ovh.net', 'Latvia', 3, 3),
  (4, 'Maris', 'Jerrans', 'mjerrans3@unesco.org', 'Sweden', 4, 4),
  (5, 'Klaus', 'Driutti', 'kdriutti4@netlog.com', 'Croatia', 5, 5),
  (6, 'Erich', 'Howels', 'ehowels5@hud.gov', 'Denmark', 6, 6),
  (7, 'Ferrel', 'Gobert', 'fgobert6@sina.com.cn', 'Romania', 7, 7),
  (8, 'Evaleen', 'Fotheringham', 'efotheringham7@japanpost.jp', 'Denmark', 8, 8),
  (9, 'Josefina', 'Dries', 'jdries8@canalblog.com', 'Latvia', 9, 9),
  (10, 'Randee', 'Beebe', 'rbeebe9@youtu.be', 'Finland', 10, 10),
  (11, 'Nisse', 'Dodworth', 'ndodwortha@paginegialle.it', 'Hungary', 11, 11),
  (12, 'Joan', 'Yukhnevich', 'jyukhnevichb@mail.ru', 'Slovakia', 12, 12),
  (13, 'Willey', 'Wallsam', 'wwallsamc@dedecms.com', 'Slovakia', 13, 13),
  (14, 'Juan', 'Toolan', 'jtooland@archive.org', 'Austria', 14, 14),
  (15, 'Bettye', 'Lismer', 'blismere@hexun.com', 'France', 15, 15),
  (16, 'Sofie', 'Fairham', 'sfairhamf@house.gov', 'Denmark', 16, 16),
  (17, 'Lucias', 'Gravet', 'lgravetg@soup.io', 'Netherlands', 17, 17),
  (18, 'Roshelle', 'Crudgington', 'rcrudgingtonh@cdbaby.com', 'Slovakia', 18, 18),
  (19, 'Honoria', 'Tawse', 'htawsei@craigslist.org', 'Hungary', 19, 19),
  (20, 'Cal', 'Goard', 'cgoardj@dion.ne.jp', 'Italy', 20, 20),
  (21, 'Philis', 'Yukhnov', 'pyukhnovk@mashable.com', 'Croatia', 21, 21),
  (22, 'Reggis', 'Duke', 'rdukel@who.int', 'France', 22, 22),
  (23, 'Hobart', 'Devine', 'hdevinem@bravesites.com', 'Cyprus', 23, 23),
  (24, 'Gaultiero', 'Spawell', 'gspawelln@a8.net', 'Denmark', 24, 24),
  (25, 'Kelbee', 'Weyman', 'kweymano@samsung.com', 'Greece', 25, 25),
  (26, 'Anselm', 'Gravestone', 'agravestonep@blogger.com', 'Sweden', 26, 26),
  (27, 'Milena', 'Pabst', 'mpabstq@youku.com', 'Netherlands', 27, 27),
  (28, 'Tamiko', 'Seabridge', 'tseabridger@craigslist.org', 'Greece', 28, 28),
  (29, 'Harley', 'Garry', 'hgarrys@webeden.co.uk', 'Hungary', 29, 29),
  (30, 'Nathalia', 'Longhorne', 'nlonghornet@latimes.com', 'France', 30, 30),
  (31, 'Hayley', 'Marryatt', 'hmarryattu@cbc.ca', 'Greece', 31, 31),
  (32, 'Martelle', 'Josham', 'mjoshamv@hhs.gov', 'Austria', 32, 32),
  (33, 'Eva', 'Keford', 'ekefordw@virginia.edu', 'Portugal', 33, 33),
  (34, 'Hurleigh', 'Scrivin', 'hscrivinx@newsvine.com', 'Cyprus', 34, 34),
  (35, 'Kiah', 'Peddar', 'kpeddary@discovery.com', 'Slovenia', 35, 35),
  (36, 'Maia', 'Coomes', 'mcoomesz@webeden.co.uk', 'Greece', 36, 36),
  (37, 'Flinn', 'Ferronet', 'fferronet10@mozilla.com', 'Romania', 37, 37),
  (38, 'Roslyn', 'Deakin', 'rdeakin11@un.org', 'Slovenia', 38, 38),
  (39, 'Cullie', 'Lemanu', 'clemanu12@shinystat.com', 'Italy', 39, 39),
  (40, 'Packston', 'Demicoli', 'pdemicoli13@parallels.com', 'Croatia', 40, 40),
  (41, 'Sylvester', 'McBrady', 'smcbrady14@netscape.com', 'France', 41, 41),
  (42, 'Jaimie', 'McLeary', 'jmcleary15@google.com.hk', 'Austria', 42, 42),
  (43, 'Batholomew', 'Fullilove', 'bfullilove16@uol.com.br', 'Croatia', 43, 43),
  (44, 'Jaclin', 'Doughty', 'jdoughty17@icio.us', 'Finland', 44, 44),
  (45, 'Anetta', 'Gillbanks', 'agillbanks18@time.com', 'Ireland', 45, 45),
  (46, 'Ebenezer', 'Rookesby', 'erookesby19@howstuffworks.com', 'Romania', 46, 46),
  (47, 'Chrissie', 'Gladman', 'cgladman1a@epa.gov', 'Netherlands', 47, 47),
  (48, 'Marta', 'Marten', 'mmarten1b@pagesperso-orange.fr', 'Czech Republic', 48, 48),
  (49, 'Eward', 'Izacenko', 'eizacenko1c@spiegel.de', 'Cyprus', 49, 49),
  (50, 'Orsa', 'Idenden', 'oidenden1d@t.co', 'Slovakia', 50, 50);